language: node_js
dist: xenial
node_js: "10"

script: grunt pack

cache:
  yarn: true

branches:
  only:
   - master
   - /^v\d+\.\d+\.\d+$/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: mbt.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_EVENT_TYPE != "cron"
