language: node_js

node_js: "6"

script: grunt pack

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
   - master
   - /^v\d+\.\d+\.\d+$/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: mbt.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_EVENT_TYPE != "cron"
