language: node_js

node_js:
 - "6"

script: grunt pack

before_script:
 - npm install

branches:
  only:
   - master

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "mbt.zip"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
