version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Grunt
          command: sudo npm install -g grunt-cli

      - run:
          name: Run tests
          command: grunt test
