version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Grunt
          command: sudo npm install -g grunt-cli

      - run:
          name: Run tests
          command: grunt lint

  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - run:
          name: Install Grunt
          command: sudo npm install -g grunt-cli

      - run:
          name: Build
          command: grunt pack

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - mbt.zip

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12

    steps:
      - checkout
      - attach_workspace:
          at: ./workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            CIRCLE_TAG="$(git tag -l --points-at HEAD)"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./workspace/mbt.zip

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
  build_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
